# Generated by Django 4.1.2 on 2022-10-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_receta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
